### ISSUE TITLE
Speedml.eda() function failed to identify Numerical Continuous features

### ISSUE THREAD

**Issue by pybokeh** [Speedml/speedml#11]
Using the titanic data sets, Speedml.eda() function failed to recognize or identify "Numerical Continuous" features.  I'm assuming it should have identified "Age" and "Fare" as "Numerical Continuous".  "Age" and "Fare" were identified by pandas as being of type float64 per my notebook [gist](http://nbviewer.jupyter.org/gist/anonymous/782d05b2f1e69d793333293edff32173).

**Comment by manavsehgal** [comment]
Yes. That is as intended. I was surprised as well at first. See, I have a 90% unique values threshold setup for continuous variables. Age only has  88 unique of 891 values and Fare has 248 of 891. So lots of repetition. Should the threshold be lower? Should I make the threshold user configurable? Is this even a fair assessment of how we define continuous versus high-cardinality? I will leave this discussion open for other users to chime in.

**Comment by manavsehgal** [comment]
Also note that there is a significant jump in model accuracy (250+ leaderboard positions jump) when I use Age and Fare as high-cardinality variables and apply `sml.feature.density()` method on them. See the companion notebook if this analysis makes more sense or I need to change my assumptions. https://github.com/Speedml/notebooks/blob/master/titanic/titanic-solution-using-speedml.ipynb

**Comment by manavsehgal** [comment]
Side note on your gist.
1. You do not need to add following code. Speedml adds it for you.

```
%matplotlib inline
import matplotlib.pyplot as plt
```

2. Do you still get the deprecation warning after refreshing the notebook and running 0.9.2?

**Comment by pybokeh** [comment]
@manavsehgal  Thank you for the explanation concerning the numerical continuous variables.

As for the deprecation, I later realized I no longer need to add the imports.  Without them, I no longer have the deprecation warning.  So no issue there.

The demo that shows the Titanic solution using Speedml is a good example.  I would recommend adding a direct link to it in your main readme to reduce the need to find it in the "Demo" hyperlink.  This is THE example that showcases the use case justification for Speedml very well.  So I think it would be beneficial to make this example highly visible somehow in the readme.  Just my opinion.

Thanks again and for your quick response!

**Comment by manavsehgal** [comment]
Great recommendation. I will add it to readme next!
