### ISSUE TITLE
there is a error when run sml=Speedml(...)  using the given example 

### ISSUE THREAD

**Issue by leepand** [Speedml/speedml#8]
the error:
>>> sml = Speedml(train='../input/train.csv', test='../input/test.csv', target = 'Survived',uid = 'PassengerId')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/speedml/__init__.py", line 46, in __init__
    base.data_n()
TypeError: unbound method data_n() must be called with Base instance as first argument (got nothing instead)

thanks

**Comment by manavsehgal** [comment]
@leepand thanks for posting this. Seems like a Python 2.7 issue. I will investigate further and revert on this thread.

**Comment by leepand** [comment]
@manavsehgal thanks for your quick response, I have just solved the problem by adding @staticmethod on the data_n() function.

**Comment by manavsehgal** [comment]
Ok. that was a quick solution, thanks. I am exploring if that is the best solution for this problem and will fix it in the next release accordingly.

**Comment by manavsehgal** [comment]
@leepand Your solution worked well. Many thanks. The fix is now live. https://github.com/Speedml/speedml/releases/tag/v0.9.2
