### ISSUE TITLE
Remove Base.inpath and Base.outpath

### ISSUE THREAD

**Issue by luxcem** [Speedml/speedml#9]
Remove https://github.com/Speedml/speedml/blob/master/speedml/__init__.py#L23-L24 that adds confusion and does not allow to use absolute path or relative path to code.

**Comment by manavsehgal** [comment]
@luxcem good observation. In release 0.9.2 coming out shortly, I am removing in/out paths for public API so you can continue using absolute/relative paths. Still using Base.outpath internally to store/retrieve xgb.fmap (feature mapping file), so you have the flexibility to configure/change this location.

**Comment by manavsehgal** [comment]
This fix is now live. https://github.com/Speedml/speedml/releases/tag/v0.9.2
